### ISSUE TITLE
Uninstall does not re-enable oculus?

### ISSUE THREAD

**Issue by Achnathon** [drosoCode/Offculus#2]
I wanted to use Medium, so tried to uninstall. This uninstalled my oculus folder, but I am still blocked from all oculus websites and services such as reinstalling the client. My IP is not blocked by Oculus, so offculus is the only perpetrator. How do I fix this? 
I am now softlocked out of my headset.

**Comment by drosoCode** [comment]
Try to open the file`C:\Windows\System32\drivers\etc\hosts` with notepad in administrator.
If still present, you can delete the following lines, otherwise, your problem is not related to offculus.
```127.0.0.1 edge-mqtt.facebook.com 
127.0.0.1 scontent.oculuscdn.com 
127.0.0.1 securecdn.oculus.com 
127.0.0.1 graph.facebook.com 
127.0.0.1 graph.oculus.com 
127.0.0.1 edge-mqtt.facebook.com 
127.0.0.1 scontent.oculuscdn.com 
127.0.0.1 securecdn.oculus.com 
127.0.0.1 graph.facebook.com `
